-- Blue Marine — Meta Ad Planner history
-- Strategic ad plans generated by Claude for Facebook/Instagram campaigns.
-- Run this once in Supabase SQL Editor:
-- https://supabase.com/dashboard/project/wqjrsmefeipvkorlbynz/sql/new

create table if not exists public.ad_planner_history (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  brief text not null,
  product_url text,
  budget_kwd numeric,
  duration_days integer,
  primary_country text,
  objective_hint text,
  plan jsonb not null,
  input_tokens integer,
  output_tokens integer
);

create index if not exists ad_planner_history_created_at_idx
  on public.ad_planner_history (created_at desc);

alter table public.ad_planner_history enable row level security;

drop policy if exists "anon read ad_planner_history" on public.ad_planner_history;
drop policy if exists "anon write ad_planner_history" on public.ad_planner_history;

create policy "anon read ad_planner_history"
  on public.ad_planner_history for select
  to anon using (true);

create policy "anon write ad_planner_history"
  on public.ad_planner_history for all
  to anon using (true) with check (true);
